# Run linters via pre-commit.
name: Linters

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  linters:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Prepare for pre-commit action
        run: |
          sudo snap install shfmt
      - uses: pre-commit/action@v2.0.2
        with:
          extra_args: --all-files --show-diff
