name: Test Poetry updater

on:
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  updater:
    runs-on: ubuntu-latest
    steps:
      - uses: Apakottur/action-poetry-package-update@v0.0.3
        with:
          base-branch: master
