name: Test Poetry updater

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  updater:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.ref }}
          echo ${{ github.sha }}
          echo ${{ github.ref_name }}
